### PR TITLE
Updated .gitignore file to include additional ignored resources.

### PR DESCRIPTION
**Pull request by danielwrobert**
Added files for logs, cache, environment, etc. to be ignored.

### CODE REVIEW

**Comment by davidakennedy** [comment]
@danielwrobert Thanks for the PR! I can see how the additional Sass ignores are handy, but do we really need all the other stuff for npm, vagrant, etc.? Just asking why? :)

**Comment by danielwrobert** [comment]
Good question. You may not necessarily _need_ all of that right now but it is a bit safer to make sure no one commits any environment files (_vagrant_). Also, if you ever end up incorporating React into the project - if that's the direction you go with the file browser, it ensures nothing from the `node_modules` dir  or NPM files and dependencies are committed.

**Comment by davidakennedy** [comment]
@danielwrobert So it sounds like we don't need any of it, save for the additional Sass stuff? I'd prefer not to add items unless we actually need them. Otherwise, it's creates questions as to why it's there.

Maybe redo the PR with a trimmed down version with just the additional Sass stuff and NPM stuff, because folks could be using Grunt or Gulp to compile Sass. Sound good?

**Comment by danielwrobert** [comment]
Sorry, I forgot to get back to you on this. Yes, that sounds good to me. I'll do that, thanks @davidakennedy!

**Comment by danielwrobert** [comment]
What are your thoughts on removing the Vagrant stuff but keeping in the NPM/Node ignores and adding in ignores for Gulp and Grunt config files?

For example:

```
# Sass
.sass-cache/
*.css.map

# CodeKit
config.codekit

# Gulp
gulpfile.js

# Grunt
gruntfile.js

# NPM and Node
# dependencies for any node modules
node_modules/
package.json
# optional npm cache directory
.npm
#logs
npm-debug.log*
logs
*.log
```

Alternatively, we can remove ​_everything_​ except for the sass ignores and leave it up to the individual to ignore what they're using to compile. But then we'd need to remove the CodeKit ignore we previously had and make sure whoever is using CodeKit doesn't commit their config.

Personally, I prefer an ignore file that catches more stuff to ensure keeping the project repo clean but that's just my workflow, and I'm happy to take whatever route y'all think is better! :)

**Comment by davidakennedy** [comment]
@danielwrobert I've been thinking about this, and what you have is a good middle ground.

I'd love to update it if/when we decide on a recommended build approach so it can be simpler.

Can you update your PR?

**Comment by danielwrobert** [comment]
> I'd love to update it if/when we decide on a recommended build approach so it can be simpler.

Yup, that sounds good to me! I'll update and push up the revision.

**Pull request merged**
