### PR TITLE
Add post styles from _s.

### LINKED ISSUE #112: Missing styles from Sass components
The following style sections seem to be missing from the Sass components:

```
/*--------------------------------------------------------------
## Posts and pages
--------------------------------------------------------------*/
.sticky {
  display: block;
}

.hentry {
  margin: 0 0 1.5em;
}

.byline,
.updated:not(.published) {
  display: none;
}

.single .byline,
.group-blog .byline {
  display: inline;
}

.page-content,
.entry-content,
.entry-summary {
  margin: 1.5em 0 0;
}

.page-links {
  clear: both;
  margin: 0 0 1.5em;
}

/*--------------------------------------------------------------
## Asides
--------------------------------------------------------------*/
.blog .format-aside .entry-title,
.archive .format-aside .entry-title {
  display: none;
}

/*--------------------------------------------------------------
## Comments
--------------------------------------------------------------*/
.comment-content a {
  word-wrap: break-word;
}

.bypostauthor {
  display: block;
}
```

These do not seem to be intentionally omitted, as the styles are still in the `style.css` file. I noticed them missing when I compiled the stylesheet for #111.

### PR DESCRIPTION
**Pull request by sarahmonster**
Fixes #112.

### CODE REVIEW

**Comment by davidakennedy** [comment]
Should this go into all branches?

**Comment by sarahmonster** [comment]
Blarrrrrrrrrrrrgh. 

PRs coming.

**Comment by karmatosed** [comment]
Do you want this closed as doing in branches?

**Comment by sarahmonster** [comment]
This needs to be done in master as well as in branches. I just need to figure out a sane way of making the change in the branches as well, which is sort of arduous because they haven't been rebased with master at any point (see #159 for an initial attempt at doing this in a branch). It also can't readily be done via the GitHub interface (at least I don't think) because it requires changing two files. 

I think I can do this by cloning the specific branches individually, then making changes and pushing them up, but this is pretty arduous. If it's important to have these done in branches now I can see if I can make that happen; otherwise I'd recommend fixing the issue in master and waiting until the types aren't locked in branches anymore to fix for types—I know the recommendation for the time being is to avoid working in the branches. :smile:

**Comment by davidakennedy** [comment]
Fixed in a recent merge with lots of changes. See: https://github.com/Automattic/theme-components/commit/b4959efe5b97f317a8422203bbb1d58d57b0b928

**Pull request closed without merging**
