### PR TITLE
Following better naming practices for page templates.

### PR DESCRIPTION
**Pull request by sixhours**
Updates JSON config files and template file names for custom page templates.

### CODE REVIEW

**Comment by sixhours** [comment]
This needs to be updated because we're moving to use front-page.php for all themes of these types, rather than a custom page template.

**Comment by sixhours** [comment]
The above is a big refactor. I'm not sure if I'm doing the config files right, since we're not technically replacing any files, just adding them to the root theme directory. Needs more testing to make sure I'm not breaking things. :)

**Comment by davidakennedy** [comment]
I'm getting some errors in the generator relating to the lines in some of the templates:

`get_template_part( 'index' );`

I'll need to dig in further.

**Comment by davidakennedy** [comment]
I believe  we fixed the above issue in a previous commit, but now I'm getting:

```
Notice: Undefined offset: 1 in /srv/www/wordpress-trunk/wp-content/themes/components.underscores.me/inc/components-generator.php on line 287

Notice: Undefined offset: 1 in /srv/www/wordpress-trunk/wp-content/themes/components.underscores.me/inc/components-generator.php on line 287

Notice: Undefined offset: 1 in /srv/www/wordpress-trunk/wp-content/themes/components.underscores.me/inc/components-generator.php on line 287

Notice: Undefined offset: 1 in /srv/www/wordpress-trunk/wp-content/themes/components.underscores.me/inc/components-generator.php on line 287
```

Will work on that.

**Pull request merged**
